### ISSUE TITLE
Can other body parts be controlled?

### ISSUE THREAD

**Issue by PlexPt** [maHidaka/ros_face#7]
It's the part that a lot of people want

**Comment by maHidaka** [comment]
yes,Possible.
Specifically, the fingertips can be controlled by attaching electrodes to the wrist.
However, because of the complex structure of human limbs, it is difficult at this stage to use this system for delicate tasks.
Also, walking on the feet is nearly impossible because of the difficulty in manipulating the major leg muscles from the surface.



This is a video of an electrically controlled finger.
As shown here, movements such as bending the fingers to roughly grasp an object or push a button are possible.

https://youtube.com/shorts/DI06kOiP-q8?feature=share

**Comment by PlexPt** [comment]
I mean the third leg

**Comment by maHidaka** [comment]
OK, I understand.
The only part of the body that can be controlled is the area where the muscles are located.

**Comment by Sologala** [comment]
Put electrodes on Pe**s ? what an odd thought.

**Comment by Magicboomliu** [comment]
@Sologala  I think it is a good idea!!!
